# Generated by Django 3.2.6 on 2021-08-08 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity_desc', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['rarity_desc'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_desc', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['type_desc'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id_tcg', models.CharField(blank=True, default='a', max_length=100)),
                ('card_name', models.CharField(max_length=250)),
                ('card_hp', models.IntegerField()),
                ('card_is_first_edition', models.BooleanField()),
                ('card_expansion', models.CharField(max_length=50)),
                ('card_price', models.FloatField()),
                ('card_image', models.CharField(default='https://http2.mlstatic.com/D_NQ_NP_681808-MLA44856858037_022021-O.jpg', max_length=250)),
                ('card_creation_date', models.DateField()),
                ('card_rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.rarity')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.type')),
            ],
            options={
                'ordering': ['card_name'],
            },
        ),
    ]
