# Generated by Django 3.2.6 on 2021-08-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id_tcg',
            field=models.CharField(default='NO_TCG', max_length=100, null=True),
        ),
    ]
