# Generated by Django 3.2.6 on 2021-08-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_alter_card_card_id_tcg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_rarity',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=250),
        ),
    ]
