# Generated by Django 3.2.6 on 2021-08-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_auto_20210808_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expansion_desc', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['expansion_desc'],
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='card_expansion',
            field=models.CharField(max_length=250),
        ),
    ]
