# Generated by Django 3.2.6 on 2021-08-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_auto_20210809_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_id_tcg',
        ),
    ]
